apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp1
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: blue
  source:
    repoURL: 'git@github.com:amizory/argocd.git'
    path: manifests
    targetRevision: HEAD
    directory:
      recurse: false
      jsonnet: {}
      exclude: '*.yaml'
      include: 'demoapp1.yaml'
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
