apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp2
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: blue
  source:
    repoURL: 'git@github.com:amizory/argocd.git'
    path: manifests
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: "*"
      kind: "*"
      jsonPointers:
        - /metadata/name
  resourceIgnoreDifferences:
    - group: "*"
      kind: "*"
      jsonPointers:
        - /metadata/name
